### ISSUE TITLE
Error detected while processing function

### ISSUE THREAD

**Issue by killtheliterate** [justinmk/vim-matchparenalways#4]
Just updated, and the following error occurs when opening a file, and each subsequent keypress.
```bash
Error detected while processing function <SNR>43_highlight_block:
line   18:
E714: List required
```

**Comment by justinmk** [comment]
something to do with https://github.com/justinmk/vim-matchparenalways/pull/3

cc @djdt

**Comment by djdt** [comment]
If you have any pairs for filetypes in your .vimrc (blockify_pairs) you will have to change them into a list by enclosing them in square brackets.

You can also have multiple types declared here.

For example:
```
let g:blockify_pairs = {
      \ 'vim':        [ '\<if\>', '\<endif\>' ],
      \ 'clojure':    [ '(', ')' ],
      \}
```
Becomes:
```
let g:blockify_pairs = {
      \ 'vim':        [[ '\<if\>', '\<endif\>' ], [ '(', ')' ]],
      \ 'clojure':    [[ '(', ')' ]],
      \}
```

**Comment by justinmk** [comment]
Thanks @djdt!

**Comment by djdt** [comment]
Any custom pairs for filetypes in your vimrc need to be changed into lists by enclosing in square braces. You can have multiple pairs for each filetype now.

For example:
```
let g:blockify_pairs = {
      \ 'vim':        [ '\<if\>', '\<endif\>' ],
      \ 'clojure':    [ '(', ')' ],
      \}
```
```
let g:blockify_pairs = {
      \ 'vim':        [[ '\<if\>', '\<endif\>' ], [ '(', ')'] ],
      \ 'clojure':    [[ '(', ')' ]],
      \}
```
